import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "League Of Legends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 text-white py-4 fixed top-0 w-full z-10">
          <nav className="container mx-auto flex justify-around">
            <h1>
              <Link href={'/'}>LOL</Link>
            </h1>
            <ul className="flex gap-3">
            <li>
              <Link href={'/campions'}>챔피언 목록</Link>
            </li>
            <li>
              <Link href={'/items'}>아이템 목록</Link>
            </li>
            <li>
              <Link href={'/rotation'}>챔피언 로테이션</Link>
            </li>
            </ul>
          </nav>
        </header>
        {children}
        </body>
    </html>
  );
}
